# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MLTECH
subtitle: EMBEDDED SYSTEM
description: >- # this means to ignore newlines until "baseurl:"
   This is the blog to sharing algorithms, techinques, tips in embedded system and computer science

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

email: sythongmta@gmail.com

twitter_username: sythong
github_username:  sythong


# Edit these details 

urls:
    - text: Blog
      url: /blog
    - text: About Me
      url: /about
    - text: project
      url : /project
    - text: Contact Me
      url : /contact

# personal infor
author_logo: profile.jpg
author: Thong Ho
author_bio: Hi, My Name is Thong Ho. I love to learn technologies.
author_email: "sythongmta@gmail.com"
author_location: Vietnam
author_website_url: "http://dientunhatrang.com"


# social links
github_username:  sythong
facebook_username: thongktdt
linkedin_username: sythong
skype_username:  thongtthq42
zalo_username: 0972879983


# Build settings
markdown: kramdown
# markdown: maruku
theme: minima
plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
# gems: [jekyll-paginate]
paginate: 6

